FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

# RUN pip install --no-cache-dir \
#     --default-timeout=120 \
#     --retries=10 \
#     -r requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python3","server.py"]

