FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    python3-dev \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /app



COPY requirements.txt .
RUN pip install --no-cache-dir \
    --default-timeout=120 \
    --retries=10 \
    -r requirements.txt


COPY . .

RUN python3 agent.py download-files

CMD ["python3", "agent.py" ,"start"] 
