# FROM python:3.11-slim

# ENV PYTHONUNBUFFERED=1

# RUN apt-get update && apt-get install -y \
#     gcc \
#     g++ \
#     python3-dev \
#   && rm -rf /var/lib/apt/lists/*
# WORKDIR /app



# COPY requirements.txt .
# RUN pip install --no-cache-dir \
#     --default-timeout=120 \
#     --retries=10 \
#     -r requirements.txt


# COPY . .

# RUN python3 agent.py download-files

# CMD ["python3", "agent.py" ,"start"] 


FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app


# Install only required runtime tools
RUN apt-get update && apt-get install -y \
    curl \
    xz-utils \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Install static ffmpeg (small & reliable)

RUN curl -L --retry 5 --retry-delay 5 \
    https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz \
    -o /tmp/ffmpeg.tar.xz \
    && tar -xJf /tmp/ffmpeg.tar.xz -C /usr/local --strip-components=1 \
    && rm -f /tmp/ffmpeg.tar.xz

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python3", "agent.py", "start"]
