FROM python:3.11-slim

ENV PYTHONUBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir \
    --default-timeout=120 \
    --retries=10 \
    -r requirements.txt


COPY . .

CMD ["python3","server.py"]

